image: archlinux
packages:
  - go

sources:
  - git@git.sr.ht:~mna/zzterm

environment:
  GO111MODULE: "on"

tasks:
  - setup: |
      cd zzterm
      go version
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b . v1.24.0
      ./golangci-lint --version

  - test: |
      cd zzterm
      go test -v -vet all -bench . -benchmem ./...

  - cover: |
      cd zzterm
      go test -cover ./...

  - lint: |
      cd zzterm
      ./golangci-lint run

triggers:
  - condition: "failure"
    action: "email"
    to: "Martin Angers <martin.n.angers+sourcehut@gmail.com>"

