image: archlinux
packages:
  - go

sources:
  - git@git.sr.ht:~mna/zzterm

environment:
  GO111MODULE: "on"

tasks:
  - setup: |
      cd zzterm
      go version
      go env
      go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      /home/build/go/bin/golangci-lint --version

  - test: |
      cd zzterm
      go test -v -vet all -bench . -benchmem ./...

  - cover: |
      cd zzterm
      go test -cover ./...

  - lint: |
      cd zzterm
      /home/build/go/bin/golangci-lint run

triggers:
  - condition: "failure"
    action: "email"
    to: "Martin Angers <martin.n.angers+sourcehut@gmail.com>"

